from __future__ import annotations

import json
from abc import abstractmethod
from datetime import datetime as Datetime

import pystac
from pydantic import BaseModel, ConfigDict, PrivateAttr, model_validator
from pystac import STACValidationError

from STACpopulator.extensions.base import Helper
from STACpopulator.models import AnyGeometry


class BaseSTAC(BaseModel):
    """Base class for STAC item data models.

    Attributes
    ----------
    geometry : AnyGeometry
        The geometry of the dataset.
    bbox : list[float]
        The bounding box of the dataset.
    start_datetime : datetime
        The start datetime of the dataset.
    end_datetime : datetime
        The end datetime of the dataset.
    id : str
        The unique identifier of the dataset. If not set, it should be generated by a subclass' `create_uid`.
    """

    # STAC item properties
    geometry: AnyGeometry | None
    bbox: list[float]
    start_datetime: Datetime = None
    end_datetime: Datetime = None
    datetime: Datetime = None
    id: str = None

    model_config = ConfigDict(populate_by_name=True, extra="ignore", arbitrary_types_allowed=True)

    # Helpers are automatically detected by being Helper subclasses
    _helpers: list[str] = PrivateAttr([])

    @model_validator(mode="after")
    def set_id(self) -> BaseSTAC:
        """Set the ID of the dataset if None."""
        if self.id is None:
            self.id = self.create_uid()
        return self

    @abstractmethod
    def create_uid(self) -> str:
        """Return a unique identifier for the dataset."""

    @model_validator(mode="after")
    def find_helpers(self) -> BaseSTAC:
        """Populate the list of extensions."""
        # Access model fields from class. From obj will be removed in pydantic v3
        for key, field in type(self).model_fields.items():
            if isinstance(field.annotation, type) and issubclass(field.annotation, Helper):
                self._helpers.append(key)
        return self

    def stac_item(self) -> pystac.Item:
        """Create a STAC item and add extensions."""
        item = pystac.Item(
            id=self.id,
            geometry=self.geometry.model_dump(),
            bbox=self.bbox,
            start_datetime=self.start_datetime,
            end_datetime=self.end_datetime,
            datetime=self.datetime,
            properties={},
        )

        # Add extensions
        for ext in self._helpers:
            getattr(self, ext).apply(item)

        try:
            item.validate()
        except STACValidationError as e:
            raise Exception("Failed to validate STAC item") from e

        return json.loads(json.dumps(item.to_dict()))
